<!DOCTYPE html>
<html lang="en-US">
<head>
<link href="style.css" rel="stylesheet" type="text/css">
</head>
<body>
        <div>
            <div class="juduljadwal">Jadwal<br>Korwil Batu</div>
            <div class="jarak">
              <select class="browser-default" onChange="window.location.href=this.value">
                <option selected disabled>Pilih Jadwal Majlis...</option>
                <option value="https://apprj.github.io/jadwal-rj.html">Malang Raya</option>
                <option value="https://apprj.github.io/jadwal-rj-jumatlegi.html">Rutinan Jum'at Legi</option>
                <option value="https://apprj.github.io/jadwal-rj-korwil-batu.html">Korwil Batu</option>
              </select>
            </div>
          <div class="container timeline">
            <div class="row">
              <div class="col s12">

                <div class="jadwal">
                  <div class="dot border-sea">
                  </div>
				  <p class="daycolor">
                    Rabu, 25 Januari 2017
                  </p>
                  <p>
                    Masjid Agung An Nur, Jl. Gajah Mada, Alun Alun Kota Batu
                  </p>
                </div>
				
                <div class="jadwal">
                  <div class="dot border-sea">
                  </div>
				  <p class="daycolor">
                    Rabu, 1 Februari 2017
                  </p>
                  <p>
                    Maqom KH. Ahmad Syadzily, Desa Pendem, Kec. Junrejo - Kota Batu						
                  </p>
                </div>
				
                <div class="jadwal">
                  <div class="dot border-sea">
                  </div>
				  <p class="daycolor">
                    Rabu, 8 Februari 2017
                  </p>
                  <p>
                    Rumah Ibu Siti (Bapak Rohim Satgas), Dsn. Temas Putuk - Kota Batu
                  </p>
                </div>
				
                <div class="jadwal">
                  <div class="dot border-sea">
                  </div>
				  <p class="daycolor">
                    Rabu, 15 Februari 2017
                  </p>
                  <p>
                    Masjid Baitul Falah, Dsn. Payan, Desa punten, Kec. Bumiaji - Kota Batu
                  </p>
                </div>
				
                <div class="jadwal">
                  <div class="dot border-sea">
                  </div>
				  <p class="daycolor">
                    Rabu, 22 Februari 2017
                  </p>
                  <p>
                    Rumah Bpk Rustamaji, Perum Bumiasri Block Q-12 Dadap Rejo
                  </p>
                </div>
				
                <div class="jadwal">
                  <div class="dot border-sea">
                  </div>
				  <p class="daycolor">
                    Rabu, 1 Maret 2017
                  </p>
                  <p>
                    Rumah Bpk M. Sirriy, Dsn.Kedung, Desa Giripurno, Kec. Bumiaji - Kota Batu
                  </p>
                </div>
				
                <div class="jadwal">
                  <div class="dot border-sea">
                  </div>
				  <p class="daycolor">
                    Rabu, 8 Maret 2017
                  </p>
                  <p>
                     Tasyakuran Khitan keluarga Bapak Hari, Dsn. Tutup, Desa Torongrejo - Kota Batu
                  </p>
                </div>
				
                <div class="jadwal">
                  <div class="dot border-sea">
                  </div>
				  <p class="daycolor">
                    Rabu, 15 Maret 2017
                  </p>
                  <p>
                    Peletakan Batu Pertama Madrasah Ibtidaiyah dan Ponpes Nurul Falah, Oro Oro Ombo Rw:01 baran
                  </p>
                </div>
				
                <div class="jadwal">
                  <div class="dot border-sea">
                  </div>
				  <p class="daycolor">
                    Rabu, 22 Maret 2017
                  </p>
                  <p>
                    Masjid Nur Asyiah, Dsn.Kekep, Selecta
                  </p>
                </div>
				
                <div class="jadwal">
                  <div class="dot border-sea">
                  </div>
				  <p class="daycolor">
                    Rabu, 29 Maret 2017
                  </p>
                  <p>
                    Panti Asuhan Al-Hidayah (Balai Desa / Proliman) Kec.Junrejo
                  </p>
                </div>
				
                <div class="jadwal">
                  <div class="dot border-sea">
                  </div>
				  <p class="daycolor">
                    Rabu, 5 April 2017
                  </p>
                  <p>
                    Rumah Bpk Nurhadi, Dsn. Ngujung, Desa Pandanrejo, Kec. Bumiaji
                  </p>
                </div>
				
                <div class="jadwal">
                  <div class="dot border-sea">
                  </div>
				  <p class="daycolor">
                    Rabu, 12 April 2017
                  </p>
                  <p>
                    Jl. Lesti utara, Kel. Ngaglik
                  </p>
                </div>
				
                <div class="jadwal">
                  <div class="dot border-sea">
                  </div>
				  <p class="daycolor">
                    Rabu, 19 April 2017
                  </p>
                  <p>
                   Masjid Al-ikhlas, Dsn. Prambatan, Desa Gunung Sari, Kec. Bumiaji
                  </p>
                </div>
				
                <div class="jadwal">
                  <div class="dot border-sea">
                  </div>
				  <p class="daycolor">
                    Rabu, 26 April 2017
                  </p>
                  <p>
                    Jamaah Tahlil, Dsn. Kedung, Desa Giripurno, Kec. Bumiaji
                  </p>
                  </div>
				
                <div class="jadwal">
                  <div class="dot border-sea">
                  </div>
				  <p class="daycolor">
                    Rabu, 3 Mei 2017
                  </p>
                  <p>
                    Masjid Baiturrohman, Jl. Darsono Ngaglik 
                  </p>
                </div>
				
                <div class="jadwal">
                  <div class="dot border-sea">
                  </div>
				  <p class="daycolor">
                    Rabu, 10 Mei 2017
                  </p>
                  <p>
                    Pemuda Pancasila, Perum Claster  - Kota Batu
                  </p>
                </div>
				
                <div class="jadwal">
                  <div class="dot border-sea">
                  </div>
				  <p class="daycolor">
                    Rabu, 17 Mei 2017
                  </p>
                  <p>
                    Madrasah Diniyyah Masjid An-Nur, Alun alun - Kota Batu
                  </p>
                </div>
				
                <div class="jadwal">
                  <div class="dot border-sea">
                  </div>
				  <p class="daycolor">
                    Rabu, 24 Mei 2017
                  </p>
                  <p>
                    Masjid Muttaqin (khoul KH.Hambali dan KH.Tohir Siddiq), Kel. Temas Putuk - Kota Batu
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
</body>
</html>
